### ISSUE TITLE
Milestone 4: Apple clone page 

### ISSUE THREAD

**Issue by Cyrus-Kiprop** [aecordova/proj4-Apple-Clone#2]
- Good work Angel. We like the way your page is styled. The precision was on point.  We would like you to do a couple of changes to the nav section of your page. The following are the issues we noticed.

- [ ] Please do add an hover effect on the navigation bar items. 

- [ ] The search icon on the far right side of the nav element, should have a different background image(search icon should be black and the background color should be white) on hover.

- [ ] The gradient on the background image  is inverted, a 180 degrees rotation on the gradient would fix the issue.
